MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_SIZES: (8, 16, 32, 64, 128)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 4
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
  ROI_MASK_HEAD:
    POOLER_RESOLUTION: 16
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    RESOLUTION: 64
    SHARE_BOX_FEATURE_EXTRACTOR: False
    CONV_LAYERS: (256, 128, 128, 64)
  MASK_ON: True
DATASETS:
  TRAIN: ('multi_train',)
  TEST: ('multi_test',)
DATALOADER:
  NUM_WORKERS: 1
SOLVER:
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (45000, 49000)
  MAX_ITER: 50000
  IMS_PER_BATCH: 32
INPUT:
  MIN_SIZE_TRAIN: 128
  MAX_SIZE_TRAIN: 128
  MIN_SIZE_TEST: 128
  MAX_SIZE_TEST: 128
  TO_BGR255: False
OUTPUT_DIR: ../../output/multi/m64_b32_pool16
